import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e1dfff",
        "surface-container-high": "#2a292f",
        "inverse-on-surface": "#303036",
        "on-secondary-fixed-variant": "#3d3e87",
        "on-surface": "#e4e1e9",
        "on-tertiary-container": "#4e3e00",
        "secondary-container": "#3d3e87",
        tertiary: "#edc221",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#231b00",
        "on-primary-container": "#faf7ff",
        "on-secondary-fixed": "#0f0d5a",
        "inverse-surface": "#e4e1e9",
        "on-surface-variant": "#c7c4d7",
        "surface-variant": "#35343a",
        "primary-fixed-dim": "#c1c1ff",
        "surface-tint": "#c1c1ff",
        "on-error": "#690005",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#131318",
        "secondary-fixed-dim": "#c1c1ff",
        "on-primary-fixed-variant": "#2e2bc2",
        "tertiary-container": "#cea700",
        secondary: "#c1c1ff",
        background: "#0e0e13",
        primary: "#c1c1ff",
        "on-primary": "#1200a9",
        "on-tertiary-fixed-variant": "#564500",
        "on-secondary": "#26276f",
        "surface-container": "#1f1f25",
        "tertiary-fixed": "#ffe083",
        "surface-container-low": "#1b1b20",
        "surface-bright": "#39383e",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#edc221",
        outline: "#908fa0",
        "surface-container-highest": "#35343a",
        "surface-container-lowest": "#0e0e13",
        "on-tertiary": "#3c2f00",
        surface: "#131318",
        "primary-container": "#5d5fef",
        "on-primary-fixed": "#07006c",
        "on-background": "#e4e1e9",
        "inverse-primary": "#4849da",
        "outline-variant": "#464555",
        "on-secondary-container": "#adaefe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-page": "40px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "card-padding": "20px",
        gutter: "24px",
        "stack-sm": "8px",
        "header-height": "64px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Manrope", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "label-md": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "data-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
