import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ─── Obsidian Glass palette ───
        accent: "#b5c4ff",
        primary: "#b5c4ff",
        "on-primary": "#00287c",
        "primary-container": "#658aff",
        "on-primary-container": "#00226d",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b5c4ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#003bae",
        "inverse-primary": "#1c53d7",
        "surface-tint": "#b5c4ff",
        secondary: "#e6feff",
        "on-secondary": "#003739",
        "secondary-container": "#00f4fe",
        "on-secondary-container": "#006c71",
        "secondary-fixed": "#63f7ff",
        "secondary-fixed-dim": "#00dce5",
        "on-secondary-fixed": "#002021",
        "on-secondary-fixed-variant": "#004f53",
        tertiary: "#ffb787",
        "on-tertiary": "#512400",
        "tertiary-container": "#e07314",
        "on-tertiary-container": "#461f00",
        "tertiary-fixed": "#ffdcc7",
        "tertiary-fixed-dim": "#ffb787",
        "on-tertiary-fixed": "#311300",
        "on-tertiary-fixed-variant": "#723600",
        warning: "#ffb787",
        "on-warning": "#512400",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#06070a",
        "on-background": "#e3e2e7",
        surface: "#121317",
        "surface-dim": "#06070a",
        "surface-bright": "#38393d",
        "surface-container-lowest": "#0d0e12",
        "surface-container-low": "#1a1b1f",
        "surface-container": "#1e1f23",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343538",
        "surface-variant": "#343538",
        "on-surface": "#e3e2e7",
        "on-surface-variant": "#c3c5d7",
        "inverse-surface": "#e3e2e7",
        "inverse-on-surface": "#2f3034",
        outline: "#8d90a0",
        "outline-variant": "#434654",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-page": "28px",
        "stack-lg": "24px",
        "stack-md": "14px",
        "card-padding": "16px",
        gutter: "20px",
        "stack-sm": "8px",
        "header-height": "56px",
        "sidebar-width": "232px",
      },
      fontFamily: {
        // Space Grotesk: headings (Obsidian Glass)
        heading: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        // Inter: body / labels / data — optimal readability
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        // JetBrains Mono: code/mono
        mono: ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-md": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["21px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "17px", fontWeight: "400" }],
        "data-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["11px", { lineHeight: "15px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      boxShadow: {
        "glow-sm": "0 0 12px rgba(0, 240, 255, 0.15)",
        "glow-md": "0 0 24px rgba(0, 240, 255, 0.2)",
        "glow-lg": "0 0 40px rgba(0, 240, 255, 0.25)",
        "glow-primary": "0 0 20px rgba(77, 162, 255, 0.3)",
        "glow-neon": "0 0 20px rgba(0, 255, 65, 0.3)",
        "neon-border": "inset 0 0 12px rgba(0, 240, 255, 0.08), 0 0 20px rgba(0, 240, 255, 0.12)",
      },
      animation: {
        "border-beam": "border-beam 4s linear infinite",
        "shimmer-slide": "shimmer-slide 3s ease-in-out infinite",
        "neon-pulse": "neon-pulse 2.5s ease-in-out infinite",
        "glow-breathe": "glow-breathe 3s ease-in-out infinite",
      },
      keyframes: {
        "border-beam": {
          "0%": { "offset-distance": "0%" },
          "100%": { "offset-distance": "100%" },
        },
        "shimmer-slide": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "neon-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        "glow-breathe": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(0, 240, 255, 0.15)" },
          "50%": { boxShadow: "0 0 35px rgba(0, 240, 255, 0.3)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
